name: Auto release
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: yarn install
      - run: yarn build

      - name: publish build files
        env:
          GH_TOKEN: '${{secrets.GH_TOKEN}}'
        run: ./.github/scripts/publish.sh
